[package]
name = "okm-dynamic"
version = "0.1.0"
edition = "2024"

[dependencies]
okm-core = { path = "../okm-core" }
serde = { version = "1", features = ["derive"], optional = true }

[dev-dependencies]
okm-derive = { path = "../okm-derive" }
okm-core = { path = "../okm-core", features = ["test-engines"] }

[features]
default = []
serde = ["dep:serde"]
