//! Preset reduce combinators (ADR-0023): the standard accumulator shapes
//! as generic `ReduceLogic` impls — one declaration line at the use site,
//! zero fold/unfold ceremony. Same write-path mechanics as a hand-written
//! logic: the derive resolves the combinator name to one of these types
//! and generates the `Reduce` impl (SLOT/GROUP) exactly as it does for a
//! user-written logic type. No wire, slot, or engine changes.
//!
//! The set is deliberately small:
//!
//! - [`Count`] — rows per group; fold +1, unfold −1 (the one exactly
//!   reversible preset — the empty-group readback is a true zero).
//! - [`Sum`] — integer total of one field per group; fold +, unfold −.
//!   Integer-only by contract: a floating-point sum is not
//!   order-independent under overwrite — float aggregates stay
//!   user-written logic where a compensation strategy is a visible choice.
//! - [`HighWater`] — running maximum of one field; unfold is a NO-OP. The
//!   watermark reading: the folded quantity never falls (assigned ids,
//!   high-water marks). For values that can legitimately shrink, the
//!   stored maximum may sit ABOVE the true extreme of the remaining rows
//!   after a delete — the contract's lossy-extreme clause, visible in
//!   the NAME at the declaration site.
//! - [`LowWater`] — running minimum; same no-op-unfold contract, mirrored.
//!   The accumulator is [`LowAcc`] (Default = the identity `u64::MAX`); a
//!   genuine minimum of `u64::MAX` is indistinguishable
//!   from an empty group on readback — an accepted corner, not a silent
//!   zero.
//!
//! `Max`/`Min` (true un-extreme unfold) are deliberately NOT shipped: in
//! a `u64` accumulator a genuine un-max needs a second structure to
//! restore the previous extreme — exactly the ceremony these presets
//! exist to retire. The HighWater/LowWater names state the real semantics.

use super::index::Document;
use super::reduce::ReduceLogic;

/// The field-aggregation source for the field-based presets
/// ([`Sum`]/[`HighWater`]/[`LowWater`]). Generated by the derive as a
/// zero-size marker type per reduce declaration — never hand-implemented.
/// The resolved value follows the ADR-0024 two-source rule with KEY WINS:
/// a declared name present in both the key and the payload encodes from
/// the key. Integer payload fields convert losslessly to u64; a key-side
/// field converts from its fixed-width BE slice (width must be 1/2/4/8).
pub trait ReduceFieldSource: 'static {
    /// The document type the aggregated field lives on.
    type Doc: Document;
    /// u64 view of the declared aggregate field.
    fn reduce_field_u64(key: &<Self::Doc as Document>::Key, document: &Self::Doc) -> u64;
}

/// Rows per group. Acc `u64`; fold +1; unfold −1.
pub struct Count<D: Document + 'static>(#[allow(dead_code)] std::marker::PhantomData<D>);

impl<D: Document + 'static> Default for Count<D> {
    fn default() -> Self {
        Count(std::marker::PhantomData)
    }
}

impl<D: Document + 'static> ReduceLogic for Count<D> {
    type Document = D;
    type Acc = u64;
    fn fold(acc: &mut Self::Acc, _key: &<Self::Document as Document>::Key, _item: &Self::Document) {
        *acc += 1;
    }
    fn unfold(acc: &mut Self::Acc, _key: &<Self::Document as Document>::Key, _item: &Self::Document) {
        *acc -= 1;
    }
}

/// Integer total of one field per group (ADR-0023: integer-only).
pub struct Sum<S: ReduceFieldSource>(#[allow(dead_code)] std::marker::PhantomData<S>);

impl<S: ReduceFieldSource> Default for Sum<S> {
    fn default() -> Self {
        Sum(std::marker::PhantomData)
    }
}

impl<S: ReduceFieldSource> ReduceLogic for Sum<S> {
    type Document = S::Doc;
    type Acc = u64;
    fn fold(acc: &mut Self::Acc, key: &<Self::Document as Document>::Key, item: &Self::Document) {
        *acc += S::reduce_field_u64(key, item);
    }
    fn unfold(acc: &mut Self::Acc, key: &<Self::Document as Document>::Key, item: &Self::Document) {
        *acc -= S::reduce_field_u64(key, item);
    }
}

/// Running maximum of one field per group; unfold is a NO-OP (the
/// watermark contract). The HighWater/LowWater name IS the semantics declaration.
pub struct HighWater<S: ReduceFieldSource>(#[allow(dead_code)] std::marker::PhantomData<S>);

impl<S: ReduceFieldSource> Default for HighWater<S> {
    fn default() -> Self {
        HighWater(std::marker::PhantomData)
    }
}

impl<S: ReduceFieldSource> ReduceLogic for HighWater<S> {
    type Document = S::Doc;
    type Acc = u64;
    fn fold(acc: &mut Self::Acc, key: &<Self::Document as Document>::Key, item: &Self::Document) {
        *acc = (*acc).max(S::reduce_field_u64(key, item));
    }
    fn unfold(_acc: &mut Self::Acc, _key: &<Self::Document as Document>::Key, _item: &Self::Document) {
        // Watermark: never falls.
    }
}

/// Running minimum of one field per group; unfold is a NO-OP (mirrors
/// [`HighWater`]). The accumulator is [`LowAcc`] — its `Default` IS the
/// identity (`u64::MAX`), because the typed write path seeds an acc with
/// `Default::default()`; a bare `u64` cannot carry the minimum's
/// identity. A genuine minimum of `u64::MAX` is indistinguishable from
/// an empty group on readback — an accepted corner, not a silent zero.
pub struct LowWater<S: ReduceFieldSource>(#[allow(dead_code)] std::marker::PhantomData<S>);

/// Minimum accumulator: `Default` = `u64::MAX` (the identity), BE wire
/// identical to a bare u64.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct LowAcc(pub u64);

impl Default for LowAcc {
    fn default() -> Self {
        LowAcc(u64::MAX)
    }
}

impl super::reduce::ReduceCodec for LowAcc {
    fn encode_acc(&self) -> Vec<u8> {
        self.0.to_be_bytes().to_vec()
    }
    fn decode_acc(bytes: &[u8]) -> Self {
        LowAcc(u64::from_be_bytes(bytes.try_into().unwrap()))
    }
}

impl<S: ReduceFieldSource> ReduceLogic for LowWater<S> {
    type Document = S::Doc;
    type Acc = LowAcc;
    fn fold(acc: &mut Self::Acc, key: &<Self::Document as Document>::Key, item: &Self::Document) {
        acc.0 = acc.0.min(S::reduce_field_u64(key, item));
    }
    fn unfold(_acc: &mut Self::Acc, _key: &<Self::Document as Document>::Key, _item: &Self::Document) {
        // Low-water mark: never rises.
    }
}
