//! Cross-document precomputation — the mutable-reduce entry (the deliberate
//! fourth primitive, ADR-0005 discipline exception, see
//! docs/INTEGRATION.md).
//!
//! Function indexes are per-document derivations: `fn(&Document)`, append-only,
//! entries born and dying with the document. Reduces span documents: a GROUP-BY
//! group's accumulated value lives in one entry whose value is
//! read-modify-written on every put/delete of a contributing document. That
//! makes it the one place okm-core value semantics are mutable — by design,
//! and only through the two user callbacks below.
//!
//! Entry layout mirrors index entries: `[ns 2B][slot 1B][group fields
//! BE]` — no key-prefix tail (the group identity IS the entry). The
//! value is the user accumulator's [`ReduceCodec`] bytes. Slots come from
//! the same declaration-order counter as indexes (append-only, never
//! reused), allocated by the derive after the last index.

use crate::engine::storage::{scan_suffix_kv, VirtualStorage};
use crate::model::index::Document;

/// Wire codec for a user accumulator. Deliberately not `serde`-shaped:
/// an accumulator is a small fixed-shape value (count, sum, count+sum
/// pair) — BE fixed width where possible, byte-transparent otherwise.
/// Implemented for `u64` (counts, sums of unsigned) and `Vec<u8>`
/// (byte-transparent escape hatch for compound accumulators).
pub trait ReduceCodec: Default + Sized {
    fn encode_acc(&self) -> Vec<u8>;
    fn decode_acc(bytes: &[u8]) -> Self;
}

impl ReduceCodec for u64 {
    fn encode_acc(&self) -> Vec<u8> {
        self.to_be_bytes().to_vec()
    }
    fn decode_acc(bytes: &[u8]) -> Self {
        assert!(bytes.len() == 8, "u64 accumulator must be 8 bytes BE");
        u64::from_be_bytes(bytes.try_into().unwrap())
    }
}

/// Signed accumulator (Sum over signed/Quant fixed-point fields): the
/// wire is the same 8-byte BE — two's complement IS the BE encoding.
impl ReduceCodec for i64 {
    fn encode_acc(&self) -> Vec<u8> {
        self.to_be_bytes().to_vec()
    }
    fn decode_acc(bytes: &[u8]) -> Self {
        assert!(bytes.len() == 8, "i64 accumulator must be 8 bytes BE");
        i64::from_be_bytes(bytes.try_into().unwrap())
    }
}

impl ReduceCodec for Vec<u8> {
    fn encode_acc(&self) -> Vec<u8> {
        self.clone()
    }
    fn decode_acc(bytes: &[u8]) -> Self {
        bytes.to_vec()
    }
}

/// The user-side half: aggregation semantics only. Implemented by the
/// application on its own type; the derive macro then generates the
/// `Reduce` impl on the SAME type (slot + group come from the
/// declaration, so the user never hand-copies them).
pub trait ReduceLogic: 'static {
    /// The document type this reduce folds over.
    type Document: Document;
    /// Accumulator state stored in the entry value.
    type Acc: ReduceCodec;
    /// Add one document into the group's accumulator. The hook receives
    /// the DECODED key reference the write path already holds (ADR-0024):
    /// quantities living in key fields are foldable without a payload
    /// mirror — a parameter pass, never a decode.
    fn fold(acc: &mut Self::Acc, key: &<Self::Document as Document>::Key, item: &Self::Document);
    /// Remove one document from the group's accumulator.
    fn unfold(acc: &mut Self::Acc, key: &<Self::Document as Document>::Key, item: &Self::Document);
}

/// The declaration-side half, generated by `#[ok_reduce(MyLogic
/// { group(a, b) })]` on the document struct. Contract:
/// - `fold`/`unfold` receive the document by immutable reference — the hook
///   never mutates the source document (put hands over `&document` before any
///   serialization; delete reaches the same hook through
///   `delete_by_pkey`'s internal get, so there is exactly one call site
///   per direction).
/// - Reversibility `unfold(fold(a, x)) = a` is the implementor's
///   obligation (count, sum, min/max qualify; median/distinct do not —
///   compound accs like count+sum for averages do).
/// - The accumulator has an independent lifetime: it survives the document
///   (a deleted last document leaves an empty group, not a deleted entry).
///   Okm does not garbage-collect zero states — a zero-detection policy
///   is the caller's, kept out of core deliberately.
pub trait Reduce: ReduceLogic {
    /// Item-local slot — allocated by the derive in declaration order
    /// within the reduce segment (0x2; independent of the index counter,
    /// ADR-0016; append-only, same discipline).
    const SLOT: crate::model::index::Slot;
    /// Group-by fields, named document fields in declaration order — key
    /// OR payload (ADR-0024: each name encodes from its own source, key
    /// via `KeyEncode`, payload via the payload walk — the
    /// `KvIndex::encode_named` two-source rule). Their encodings form the
    /// entry's group segment (the sort key). Read-side probes name the
    /// same fields with the same encodings, mirroring the func-index
    /// probe rule. A name in BOTH sources is a compile error.
    const GROUP: &'static [&'static str];

    /// Encoded group segment: the named GROUP fields' payload encodings
    /// in declaration order. Required (not defaulted): the implementation
    /// is generated by the derive via the document's named-field walk — the
    /// same encoders the index layer uses, so byte compatibility holds.
    fn group_bytes(key: &<Self::Document as Document>::Key, document: &Self::Document) -> Vec<u8>;

    /// Full entry key `[ns 2B][slot 2B][group segment]`.
    fn entry_key(ns_prefix: &[u8], key: &<Self::Document as Document>::Key, document: &Self::Document) -> Vec<u8> {
        let g = Self::group_bytes(key, document);
        let mut buf = Vec::with_capacity(ns_prefix.len() + 2 + g.len());
        buf.extend_from_slice(ns_prefix);
        buf.extend_from_slice(&Self::SLOT.to_be_bytes());
        buf.extend_from_slice(&g);
        buf
    }
}

/// Read one group's current accumulator (None = group not yet created).
pub fn reduce_get<S: VirtualStorage, A: Reduce>(
    store: &S,
    ns_prefix: &[u8],
    key: &<A::Document as Document>::Key,
    document: &A::Document,
) -> Option<A::Acc> {
    let bytes = store.get(&A::entry_key(ns_prefix, key, document))?;
    Some(A::Acc::decode_acc(&bytes))
}

/// Scan every group of one reduce: full group segment + acc bytes.
/// Prefix `[ns 2B][slot 1B]` — each suffix is the group segment.
pub fn scan_reduces<S: VirtualStorage, A: Reduce>(
    store: &S,
    ns_prefix: &[u8],
) -> Vec<(Vec<u8>, A::Acc)> {
    let mut prefix = Vec::with_capacity(ns_prefix.len() + 2);
    prefix.extend_from_slice(ns_prefix);
    prefix.extend_from_slice(&A::SLOT.to_be_bytes());
    scan_suffix_kv(store, &prefix)
        .into_iter()
        .map(|(suffix, value)| (suffix, A::Acc::decode_acc(&value)))
        .collect()
}

/// The write-side hook on the Document trait (default no-op: undecorated
/// documents keep their zero-cost put path). Generated by
/// `#[derive(DocumentEncode)]` when `#[ok_reduce(..)]` declarations exist:
/// one closure per declared reduce, each doing the full read-
/// modify-write for its group — get acc, decode, fold/unfold, encode,
/// put. Same store instance as the document write, so atomicity holds within
/// one engine (same boundary as index entries).
pub fn apply_row<S: VirtualStorage, R: Document>(
    store: &mut S,
    key: &R::Key,
    document: &R,
    ns_prefix: &[u8],
    add: bool,
) {
    R::__okm_apply_reduces(store, key, document, ns_prefix, add);
}
