//! Edge side: the [`KvEdge`] trait and the direction-bit header.
//!
//! SQL foreign keys become explicit forward+reverse double-written keys.
//! Writing links both directions atomically; deleting removes both sides.
//! The edge struct's declaration doubles as the E-R documentation — the
//! relationship encoding and the key generation live in the same place.

use crate::key::KeyEncode;

/// Header encoding: ns occupies the low 15 bits of a u16, the top bit is
/// the direction bit (FWD = 0, REV = 1).
///
/// The semantic namespace space is 32768 (niche decision, finalized
/// 2026-09-06 — see `docs/adr/0001-direction-bit-niche.md`); the 2-byte
/// fixed-width header preserves prefix-scan semantics.
pub const NS_BITS: u16 = 15;
pub const DIR_BIT: u16 = 1 << NS_BITS; // 0x8000

#[inline]
pub fn head_bytes(ns: u16, rev: bool) -> [u8; 2] {
    (((ns & (DIR_BIT - 1)) << 1) | (rev as u16)).to_be_bytes()
}

/// Bidirectional edge contract. `A` = first field (source), `B` = second
/// field (destination).
///
/// `A_HEAD` / `B_HEAD` are generated by the `EdgeEncode` macro from
/// `#[kv_head(...)]` (empty = full identity).
pub trait KvEdge: Sized {
    type A: KeyEncode;
    type B: KeyEncode;
    const NS: u16;
    /// Identity fields of A for this edge (declaration-order prefix of A's
    /// fields; empty = full identity).
    const A_HEAD: &'static [&'static str];
    /// Identity fields of B for this edge.
    const B_HEAD: &'static [&'static str];
    fn a(&self) -> &Self::A;
    fn b(&self) -> &Self::B;
    fn from_parts(a: Self::A, b: Self::B) -> Self;

    fn encode_a_head(buf: &mut Vec<u8>, a: &Self::A) -> usize {
        if Self::A_HEAD.is_empty() {
            buf.extend_from_slice(&a.encode());
            Self::A::KEY_LEN
        } else {
            a.encode_prefix_named(buf, Self::A_HEAD)
        }
    }
    fn a_head_width() -> usize {
        if Self::A_HEAD.is_empty() {
            Self::A::KEY_LEN
        } else {
            Self::A::prefix_width(Self::A_HEAD)
        }
    }
    fn encode_b_head(buf: &mut Vec<u8>, b: &Self::B) -> usize {
        if Self::B_HEAD.is_empty() {
            buf.extend_from_slice(&b.encode());
            Self::B::KEY_LEN
        } else {
            b.encode_prefix_named(buf, Self::B_HEAD)
        }
    }
    fn b_head_width() -> usize {
        if Self::B_HEAD.is_empty() {
            Self::B::KEY_LEN
        } else {
            Self::B::prefix_width(Self::B_HEAD)
        }
    }

    /// `[head 2B: ns<<1 | dir][A·identity][B·identity]`
    fn forward_key(&self) -> Vec<u8> {
        let mut k = Vec::with_capacity(2 + Self::a_head_width() + Self::b_head_width());
        k.extend_from_slice(&head_bytes(Self::NS, false));
        Self::encode_a_head(&mut k, self.a());
        Self::encode_b_head(&mut k, self.b());
        k
    }
    /// `[head 2B: ns<<1 | dir][B·identity][A·identity]`
    fn reverse_key(&self) -> Vec<u8> {
        let mut k = Vec::with_capacity(2 + Self::a_head_width() + Self::b_head_width());
        k.extend_from_slice(&head_bytes(Self::NS, true));
        Self::encode_b_head(&mut k, self.b());
        Self::encode_a_head(&mut k, self.a());
        k
    }
}
