//! Secondary indexes (access methods) and the [`Row`] payload contract.
//!
//! Index key layout (ADR-0005/0006): `[ns 2B][slot 1B][indexed fields BE]
//! [includes fields BE][primary key ID]`, value empty. Slot 0 is reserved
//! for the table's primary keys (`[ns 2B][0x00][key payload]`), so an
//! access method's entries never collide with the table segment and one
//! ns-prefix scan still covers everything. Slots 1, 2, … are allocated by
//! attribute order inside one item (macro-side counter, never reused —
//! hole discipline same as ns IDs). The primary key ID is always the full
//! key encoding appended at the tail, so the layout is uniform regardless
//! of how many fields the index covers.

use crate::engine::KvEngine;
use crate::key::KeyEncode;

/// Slot reserved for a table's primary keys inside its ns segment.
pub const PRIMARY_SLOT: u8 = 0;

/// Value-side payload contract (ADR-0004/0006): a row = identity (its key)
/// plus payload fields, encoded as TLV — one `[tag u8][len u32 BE]
/// [value BE]` record per field, in declaration order.
///
/// Generated by `#[derive(RowEncode)]`; the declaration is the single
/// source for value encoding, index slots, and snapshot columns.
pub trait Row: Sized + Clone {
    /// Identity type this row hangs off (from `#[kv_ref(...)]`).
    type Key: KeyEncode;
    /// Payload field name → width table, declaration order (snapshot columns).
    const PAYLOAD_FIELDS: &'static [(&'static str, usize)];
    /// TLV payload encoding of the attribute fields.
    fn encode_payload(&self) -> Vec<u8>;
    /// Decode payload; `b` holds only the TLV region (no key bytes).
    fn decode_payload(b: &[u8]) -> Self;
    /// All declared access methods' index entries for `key`, in slot order.
    /// Generated; lets Table::put/delete cover every declared index without
    /// a runtime registry (the declaration IS the registry).
    fn index_entries(key: &Self::Key, ns: u16) -> Vec<Vec<u8>>;

    /// Assembly-point constructor: builds the row's `Table` binding this
    /// row type to its `#[kv_ref]` key. The key type never appears at the
    /// call site — it is already pinned by `Self::Key`.
    fn table<S: KvEngine>(store: S, ns: u16) -> crate::table::Table<S, Self::Key, Self> {
        crate::table::Table::new(store, ns)
    }
}

/// One access method over a table. Implemented by generated marker
/// structs (`#[derive(RowEncode)]` + `#[kv_index(...)]`); slots derive
/// from the table's ns — indexes never take manual namespace IDs.
pub trait KvIndex {
    type Key: KeyEncode;
    /// Item-local slot, allocated by attribute order (1, 2, …; 0 = primary).
    const SLOT: u8;
    /// Indexed fields, declaration-order prefix of the key struct's fields.
    const FIELDS: &'static [&'static str];
    /// Covering fields continuing the prefix (may be empty). `includes`
    /// makes the scan self-sufficient — a materialized view for high-fanout
    /// queries (ADR-0006), never a default optimization.
    const INCLUDES: &'static [&'static str];

    /// All fields carried before the primary key ID.
    fn carried() -> Vec<&'static str> {
        Self::FIELDS.iter().chain(Self::INCLUDES).copied().collect()
    }

    /// Index header `[ns 2B][slot 1B]`; ns comes from the engine's segment
    /// registry, passed in by the assembly point (Table) — the index itself
    /// stays ns-agnostic.
    fn header(ns: u16) -> [u8; 3] {
        let b = ns.to_be_bytes();
        [b[0], b[1], Self::SLOT]
    }

    /// Carried-segment byte width: `prefix_width(fields ++ includes)`.
    fn carried_width() -> usize {
        <Self::Key as KeyEncode>::prefix_width(&Self::carried())
    }

    /// Full index entry key: header + carried fields + full key as the
    /// primary key ID. The carried segment is the declaration-order prefix
    /// of the key's own encoding — no separate encoding pass, just a slice.
    fn encode_entry(ns: u16, key: &Self::Key) -> Vec<u8> {
        let enc = key.encode();
        let w = Self::carried_width();
        debug_assert!(enc.len() >= w, "carried width exceeds key length");
        let mut buf = Vec::with_capacity(3 + w + Self::Key::KEY_LEN);
        buf.extend_from_slice(&Self::header(ns));
        buf.extend_from_slice(&enc[..w]);
        buf.extend_from_slice(&enc); // primary key ID at the tail
        buf
    }

    /// Scan prefix for a leftmost-prefix match: header + the encoded bytes
    /// of the leading carried fields. `encoded` is the caller-side encoding
    /// of the match values (e.g. `7u32.to_be_bytes()` for `org_id`) and must
    /// not exceed the carried width.
    fn entry_prefix(ns: u16, encoded: &[u8]) -> Vec<u8> {
        debug_assert!(
            encoded.len() <= Self::carried_width(),
            "encoded prefix exceeds carried width"
        );
        let mut buf = Vec::with_capacity(3 + encoded.len());
        buf.extend_from_slice(&Self::header(ns));
        buf.extend_from_slice(encoded);
        buf
    }
}

/// Leftmost-prefix scan over an index: returns the decoded primary keys.
///
/// `encoded` is the concatenated big-endian encoding of the leading carried
/// fields to match (empty slice = scan the whole index). Each entry's suffix
/// is `[unmatched carried bytes][primary key ID]`; the primary key ID is the
/// last `KEY_LEN` bytes regardless of what the index covers, so decoding
/// never depends on the index definition.
pub fn scan_index<S: KvEngine, I: KvIndex>(store: &S, ns: u16, encoded: &[u8]) -> Vec<I::Key> {
    let p = I::entry_prefix(ns, encoded);
    let kl = I::Key::KEY_LEN;
    store
        .scan_suffix(&p)
        .iter()
        .map(|suffix| {
            assert!(suffix.len() >= kl, "index entry shorter than a primary key");
            I::Key::decode(&suffix[suffix.len() - kl..])
        })
        .collect()
}
