//! Key side: the [`KeyEncode`] trait and [`PrefixKey`].
//!
//! A key struct derived with `#[derive(KeyEncode)]` **is** the DDL: SQL
//! defines table structure, the Rust struct defines key encoding, and the
//! compiler enforces format consistency. Fields are big-endian, fixed
//! width, no separators — decoding is pure pointer slicing.

/// Fixed-width key encoding contract.
///
/// `KEY_LEN` / `FIELD_WIDTHS` / `encode` are generated by
/// `#[derive(KeyEncode)]`; `encode_prefix_named` is the "truncated
/// identity" primitive: encode the first N fields in declaration order.
pub trait KeyEncode: Sized + Clone {
    /// Total encoded byte count (payload only, namespace header excluded).
    const KEY_LEN: usize;
    /// Field name → width table (declaration order). The edge macro uses it
    /// to validate at runtime that `kv_head` names a legal declaration-order
    /// prefix.
    const FIELD_WIDTHS: &'static [(&'static str, usize)];
    fn encode(&self) -> Vec<u8>;
    fn decode(bytes: &[u8]) -> Self;
    /// Field descriptors, declaration order — the key's single field list
    /// with primitive kinds (Arrow schema / column builders, ADR-0007).
    const FIELDS: &'static [crate::field::FieldDesc] = &[];
    /// Encode the first `names.len()` fields in declaration order;
    /// `names` must be a declaration-order prefix (first mismatch panics).
    fn encode_prefix_named(&self, buf: &mut Vec<u8>, names: &[&str]) -> usize;
    /// Width of the corresponding prefix.
    fn prefix_width(names: &[&str]) -> usize;
}

/// Decode product of a truncated identity: the full `A` decode plus the
/// number of bytes consumed by the identity prefix.
///
/// Prefix fields are trustworthy; trailing fields are garbage read past the
/// boundary into B's encoding region — callers must use only the prefix
/// fields, or take `decoded`'s prefix portion to scan the main table.
pub struct PrefixKey<A> {
    pub decoded: A,
    /// Bytes consumed by the identity prefix (= sum of `kv_head` field widths).
    pub taken: usize,
}
