//! Edge side: the [`KvEdge`] trait and slot-addressed edge keys
//! (PLAN Phase 10 — supersedes the ADR-0001 direction-bit niche).
//!
//! SQL foreign keys become explicit forward+reverse double-written keys.
//! Writing links both directions atomically; deleting removes both sides.
//! The edge struct's declaration doubles as the E-R documentation — the
//! relationship encoding and the key generation live in the same place.
//!
//! Layout: `[ns 2B BE][slot 1B][endpoint identities]` — the same header
//! discipline as tables (raw ns, no transform, full 16-bit ns space).
//! Direction is a slot: 14 = forward (source identity first), 15 =
//! reverse (destination identity first). The saved byte of the old
//! niche cost a transform, a halved ns space, and collection/edge layout
//! divergence; one slot byte restores uniformity.

use crate::index::{EDGE_FWD_SLOT, EDGE_REV_SLOT};
use crate::key::KeyEncode;

/// Bidirectional edge contract. `A` = first field (source), `B` = second
/// field (destination).
///
/// `A_HEAD` / `B_HEAD` are generated by the `EdgeEncode` macro from
/// `#[ok_head(...)]` (empty = full identity).
pub trait KvEdge: Sized {
    type A: KeyEncode;
    type B: KeyEncode;
    const NS: u16;
    /// Identity fields of A for this edge (declaration-order prefix of A's
    /// fields; empty = full identity).
    const A_HEAD: &'static [&'static str];
    /// Identity fields of B for this edge.
    const B_HEAD: &'static [&'static str];
    fn a(&self) -> &Self::A;
    fn b(&self) -> &Self::B;
    fn from_parts(a: Self::A, b: Self::B) -> Self;

    fn encode_a_head(buf: &mut Vec<u8>, a: &Self::A) -> usize {
        if Self::A_HEAD.is_empty() {
            buf.extend_from_slice(&a.encode());
            Self::A::KEY_LEN
        } else {
            a.encode_prefix_named(buf, Self::A_HEAD)
        }
    }
    fn a_head_width() -> usize {
        if Self::A_HEAD.is_empty() {
            Self::A::KEY_LEN
        } else {
            Self::A::prefix_width(Self::A_HEAD)
        }
    }
    fn encode_b_head(buf: &mut Vec<u8>, b: &Self::B) -> usize {
        if Self::B_HEAD.is_empty() {
            buf.extend_from_slice(&b.encode());
            Self::B::KEY_LEN
        } else {
            b.encode_prefix_named(buf, Self::B_HEAD)
        }
    }
    fn b_head_width() -> usize {
        if Self::B_HEAD.is_empty() {
            Self::B::KEY_LEN
        } else {
            Self::B::prefix_width(Self::B_HEAD)
        }
    }

    /// `[ns 2B BE][slot 14][A·identity][B·identity]`
    fn forward_key(&self) -> Vec<u8> {
        let mut k = Vec::with_capacity(3 + Self::a_head_width() + Self::b_head_width());
        k.extend_from_slice(&Self::NS.to_be_bytes());
        k.push(EDGE_FWD_SLOT);
        Self::encode_a_head(&mut k, self.a());
        Self::encode_b_head(&mut k, self.b());
        k
    }
    /// `[ns 2B BE][slot 15][B·identity][A·identity]`
    fn reverse_key(&self) -> Vec<u8> {
        let mut k = Vec::with_capacity(3 + Self::a_head_width() + Self::b_head_width());
        k.extend_from_slice(&Self::NS.to_be_bytes());
        k.push(EDGE_REV_SLOT);
        Self::encode_b_head(&mut k, self.b());
        Self::encode_a_head(&mut k, self.a());
        k
    }
}
