//! Cross-row precomputation — the mutable-reduce entry (the deliberate
//! fourth primitive, ADR-0005 discipline exception, see
//! docs/INTEGRATION.md).
//!
//! Function indexes are per-row derivations: `fn(&Row)`, append-only,
//! entries born and dying with the row. Reduces span rows: a GROUP-BY
//! group's accumulated value lives in one entry whose value is
//! read-modify-written on every put/delete of a contributing row. That
//! makes it the one place okm-core value semantics are mutable — by design,
//! and only through the two user callbacks below.
//!
//! Entry layout mirrors index entries: `[ns 2B][slot 1B][group fields
//! BE]` — no key-prefix tail (the group identity IS the entry). The
//! value is the user accumulator's [`ReduceCodec`] bytes. Slots come from
//! the same declaration-order counter as indexes (append-only, never
//! reused), allocated by the derive after the last index.

use crate::engine::KvEngine;
use crate::index::Row;

/// Wire codec for a user accumulator. Deliberately not `serde`-shaped:
/// an accumulator is a small fixed-shape value (count, sum, count+sum
/// pair) — BE fixed width where possible, byte-transparent otherwise.
/// Implemented for `u64` (counts, sums of unsigned) and `Vec<u8>`
/// (byte-transparent escape hatch for compound accumulators).
pub trait ReduceCodec: Default + Sized {
    fn encode_acc(&self) -> Vec<u8>;
    fn decode_acc(bytes: &[u8]) -> Self;
}

impl ReduceCodec for u64 {
    fn encode_acc(&self) -> Vec<u8> {
        self.to_be_bytes().to_vec()
    }
    fn decode_acc(bytes: &[u8]) -> Self {
        assert!(bytes.len() == 8, "u64 accumulator must be 8 bytes BE");
        u64::from_be_bytes(bytes.try_into().unwrap())
    }
}

impl ReduceCodec for Vec<u8> {
    fn encode_acc(&self) -> Vec<u8> {
        self.clone()
    }
    fn decode_acc(bytes: &[u8]) -> Self {
        bytes.to_vec()
    }
}

/// The user-side half: aggregation semantics only. Implemented by the
/// application on its own type; the derive macro then generates the
/// `Reduce` impl on the SAME type (slot + group come from the
/// declaration, so the user never hand-copies them).
pub trait ReduceLogic: 'static {
    /// The row type this reduce folds over.
    type Row: Row;
    /// Accumulator state stored in the entry value.
    type Acc: ReduceCodec;
    /// Add one row into the group's accumulator.
    fn fold(acc: &mut Self::Acc, item: &Self::Row);
    /// Remove one row from the group's accumulator.
    fn unfold(acc: &mut Self::Acc, item: &Self::Row);
}

/// The declaration-side half, generated by `#[kv_reduce(MyLogic
/// { group(a, b) })]` on the row struct. Contract:
/// - `fold`/`unfold` receive the row by immutable reference — the hook
///   never mutates the source row (put hands over `&row` before any
///   serialization; delete reaches the same hook through
///   `delete_by_pkey`'s internal get, so there is exactly one call site
///   per direction).
/// - Reversibility `unfold(fold(a, x)) = a` is the implementor's
///   obligation (count, sum, min/max qualify; median/distinct do not —
///   compound accs like count+sum for averages do).
/// - The accumulator has an independent lifetime: it survives the row
///   (a deleted last row leaves an empty group, not a deleted entry).
///   Okm does not garbage-collect zero states — a zero-detection policy
///   is the caller's, kept out of core deliberately.
pub trait Reduce: ReduceLogic {
    /// Item-local slot — allocated by the derive in declaration order
    /// (continuing after the last index; append-only, same discipline).
    const SLOT: u8;
    /// Group-by fields, named row payload fields in declaration order —
    /// their encodings form the entry's group segment (the sort key).
    /// Read-side probes name the same fields with the same encodings,
    /// mirroring the func-index probe rule.
    const GROUP: &'static [&'static str];

    /// Encoded group segment: the named GROUP fields' payload encodings
    /// in declaration order. Required (not defaulted): the implementation
    /// is generated by the derive via the row's named-field walk — the
    /// same encoders the index layer uses, so byte compatibility holds.
    fn group_bytes(key: &<Self::Row as Row>::Key, row: &Self::Row) -> Vec<u8>;

    /// Full entry key `[ns 2B][slot 1B][group segment]`.
    fn entry_key(table_ns: &[u8], key: &<Self::Row as Row>::Key, row: &Self::Row) -> Vec<u8> {
        let g = Self::group_bytes(key, row);
        let mut buf = Vec::with_capacity(table_ns.len() + 1 + g.len());
        buf.extend_from_slice(table_ns);
        buf.push(Self::SLOT);
        buf.extend_from_slice(&g);
        buf
    }
}

/// Read one group's current accumulator (None = group not yet created).
pub fn reduce_get<S: KvEngine, A: Reduce>(
    store: &S,
    table_ns: &[u8],
    key: &<A::Row as Row>::Key,
    row: &A::Row,
) -> Option<A::Acc> {
    let bytes = store.get(&A::entry_key(table_ns, key, row))?;
    Some(A::Acc::decode_acc(&bytes))
}

/// Scan every group of one reduce: full group segment + acc bytes.
/// Prefix `[ns 2B][slot 1B]` — each suffix is the group segment.
pub fn scan_reduces<S: KvEngine, A: Reduce>(
    store: &S,
    table_ns: &[u8],
) -> Vec<(Vec<u8>, A::Acc)> {
    let mut prefix = Vec::with_capacity(table_ns.len() + 1);
    prefix.extend_from_slice(table_ns);
    prefix.push(A::SLOT);
    store
        .scan_suffix_kv(&prefix)
        .into_iter()
        .map(|(suffix, value)| (suffix, A::Acc::decode_acc(&value)))
        .collect()
}

/// The write-side hook on the Row trait (default no-op: undecorated
/// rows keep their zero-cost put path). Generated by
/// `#[derive(RowEncode)]` when `#[kv_reduce(..)]` declarations exist:
/// one closure per declared reduce, each doing the full read-
/// modify-write for its group — get acc, decode, fold/unfold, encode,
/// put. Same store instance as the row write, so atomicity holds within
/// one engine (same boundary as index entries).
pub fn apply_row<S: KvEngine, R: Row>(
    store: &mut S,
    key: &R::Key,
    row: &R,
    table_ns: &[u8],
    add: bool,
) {
    R::__okm_apply_reduces(store, key, row, table_ns, add);
}
